name: CI Validacao de PR

on:
  pull_request:
    branches:
      - main

jobs:
  validar_trio_e_codigo:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar o código
      uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Rodar a bateria de testes
      run: python -m unittest test_sistema.py